# Generated by Django 2.1.4 on 2019-01-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_acelerografo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acelerografo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='acelerografo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
