# Generated by Django 2.1.4 on 2019-02-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190115_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aceleracion',
            name='sismo',
        ),
        migrations.DeleteModel(
            name='Sismo',
        ),
    ]
