# Generated by Django 2.1.4 on 2019-02-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190201_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceleracion',
            name='compente',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='aceleracion',
            name='frecuencia',
            field=models.CharField(max_length=15),
        ),
    ]
